"""Golden vectors: the cross-language byte-identity contract.

These files are generated by ``tests/gen_vectors.py`` from the Python kernel and
replayed here; P1's TypeScript ``@edgeproc/avow`` suite replays the SAME files
byte-for-byte. RFC 8785 number serialization (ECMAScript shortest round-trip) is the
known hazard, so the vectors deliberately include floats (0.5, 0.1, 1e21, -0.0, 1e-7).
Any divergence fails here, in CI — never in production."""

from __future__ import annotations

import json
from pathlib import Path

from pydantic import BaseModel, ConfigDict

from avow import SignedReceipt, canonical_bytes, content_hash, verify_signature

_CANONICAL = Path("testdata/vectors/canonical.json")
_RECEIPTS = Path("testdata/vectors/receipts.json")


class _Subject(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")
    kind: str
    score: float
    tags: tuple[str, ...]


def test_canonical_vectors_replay() -> None:
    vectors = json.loads(_CANONICAL.read_text(encoding="utf-8"))
    # incl. floats 0.5, 0.1, 1e21, -0.0, unicode, nesting, empty, key-shuffle
    assert len(vectors) >= 8
    for v in vectors:
        assert canonical_bytes(v["payload"]).hex() == v["canonical_hex"]
        assert content_hash(v["payload"]) == v["content_hash"]


def test_receipt_vectors_verify() -> None:
    data = json.loads(_RECEIPTS.read_text(encoding="utf-8"))
    assert len(data["receipts"]) >= 1
    for r in data["receipts"]:
        receipt = SignedReceipt[_Subject](
            payload=_Subject(**r["payload"]),
            payload_hash=r["payload_hash"],
            public_key=data["public_key"],
            signature=r["signature"],
        )
        verify_signature(receipt, expected_public_key=data["public_key"])
