"""Golden vectors: the cross-language byte-identity contract.

These files are generated by ``tests/gen_vectors.py`` from the Python kernel and
replayed here; P1's TypeScript ``@edgeproc/avow`` suite replays the SAME files
byte-for-byte. RFC 8785 number serialization (ECMAScript shortest round-trip) is the
known hazard, so vectors include safe integer endpoints, fractions, -0.0, and 1e-7.
Any divergence fails here, in CI — never in production."""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from nacl.signing import SigningKey

from avow import (
    SignedReceipt,
    canonical_bytes,
    content_hash,
    public_key_hex,
    sign_payload,
    verify_signature,
)
from avow.canonical import JsonValue
from avow.errors import CanonicalizationFailed

_CANONICAL = Path("testdata/vectors/canonical.json")
_RECEIPTS = Path("testdata/vectors/receipts.json")
_INVALID = Path("testdata/vectors/invalid.json")

_JSON_SHAPES = {"array", "boolean", "null", "number", "object", "string"}
_INVALID_NAMES = {
    "lone_high_surrogate",
    "lone_high_surrogate_key",
    "lone_low_surrogate",
    "lone_low_surrogate_key",
    "nested_lone_high_surrogate_key",
    "nested_lone_low_surrogate_key",
    "nested_lone_surrogate",
    "unsafe_integer",
    "unsafe_integer_float",
    "unsafe_negative_integer",
}
_TYPE_SHAPES: dict[type[object], str] = {
    bool: "boolean",
    list: "array",
    dict: "object",
    str: "string",
}


def _json_shape(value: JsonValue) -> str:
    if value is None:
        return "null"
    return _TYPE_SHAPES.get(type(value), "number")


def test_should_replay_every_canonical_shape() -> None:
    # Given
    vectors = json.loads(_CANONICAL.read_text(encoding="utf-8"))

    # Then
    assert len(vectors) >= 8
    assert {_json_shape(v["payload"]) for v in vectors} == _JSON_SHAPES
    for v in vectors:
        assert canonical_bytes(v["payload"]).hex() == v["canonical_hex"]
        assert content_hash(v["payload"]) == v["content_hash"]


def _assert_receipt_vector(r: dict[str, JsonValue], data: dict[str, JsonValue]) -> None:
    assert r["schema"] == "avow.receipt/v1"
    receipt = SignedReceipt[JsonValue](
        schema=str(r["schema"]),
        payload=r["payload"],
        payload_hash=str(r["payload_hash"]),
        public_key=str(data["public_key"]),
        signature=str(r["signature"]),
    )
    verify_signature(receipt, expected_public_key=str(data["public_key"]))
    regenerated = sign_payload(r["payload"], SigningKey(bytes.fromhex(str(data["seed_hex"]))))
    assert regenerated.receipt_schema == r["schema"]
    assert regenerated.payload_hash == r["payload_hash"]
    assert regenerated.public_key == data["public_key"]
    assert regenerated.signature == r["signature"]


def test_should_replay_every_receipt_shape() -> None:
    # Given
    data = json.loads(_RECEIPTS.read_text(encoding="utf-8"))
    receipts = data["receipts"]

    # Then
    assert receipts
    assert "json_receipts" not in data
    assert {_json_shape(r["payload"]) for r in receipts} == _JSON_SHAPES
    assert public_key_hex(SigningKey(bytes.fromhex(data["seed_hex"]))) == data["public_key"]
    for receipt in receipts:
        _assert_receipt_vector(receipt, data)


def test_should_reject_every_invalid_vector() -> None:
    # Given
    vectors = json.loads(_INVALID.read_text(encoding="utf-8"))

    # Then
    assert {v["name"] for v in vectors} == _INVALID_NAMES
    for vector in vectors:
        with pytest.raises(CanonicalizationFailed):
            canonical_bytes(vector["payload"])
